### ISSUE TITLE
cmake: check for all needed dependencies

### ISSUE THREAD

**Issue by lodle** [desura/desura-app#243]
_Issue by **[karolherbst](https://github.com/karolherbst)** from Tuesday Jun 12, 2012 at 16:57 GMT_
_Originally opened as https://github.com/desura/Desurium/issues/243_

----

some dependencies are not checked by cmake:
* patch
* automake
* compiler checks:
 * gcc-4.5
 * clang-3.1

feel free to report more deps (I will update this list)

**Comment by TheBeastie** [comment]
Dependencies for the Linux build were added. If we missed anything, please create a new issue for it.
ty.
