### ISSUE TITLE
desura: free(): invalid next size (normal)

### ISSUE THREAD

**Issue by lodle** [desura/desura-app#246]
_Issue by **[yurikoles](https://github.com/yurikoles)** from Sunday Jun 17, 2012 at 12:17 GMT_
_Originally opened as https://github.com/desura/Desurium/issues/246_

----

http://pastebin.com/984DVB47
I just launched the client and tried to download my games.
also desura: double free or corruption (out) http://pastebin.com/59eh2Msy

**Comment by TheBeastie** [comment]
Closing as isolated and too old.
