### ISSUE TITLE
curl 7.28 with gnutls 3 prevents login

### ISSUE THREAD

**Issue by lodle** [desura/desura-app#337]
_Issue by **[TheSiege](https://github.com/TheSiege)** from Saturday Oct 20, 2012 at 14:20 GMT_
_Originally opened as https://github.com/desura/Desurium/issues/337_

----

gets a certificate failed to get error at login

**Comment by TheBeastie** [comment]
With this:
https://github.com/desura/desura-app/commit/8ea7d490c105bfd5f2c94a6aa1a4eba5f160562d
Curl updates, cert updates, etc. I'm marking this closed.  If anyone gets these errors again - please create a new issue.
