### ISSUE TITLE
Cef is not working behind a proxy

### ISSUE THREAD

**Issue by lodle** [desura/desura-app#409]
_Issue by **[karolherbst](https://github.com/karolherbst)** from Friday Jan 18, 2013 at 13:46 GMT_
_Originally opened as https://github.com/desura/Desurium/issues/409_

----

encountered in a proxy setup

**Comment by TheBeastie** [comment]
Fixed in:
https://github.com/desura/desura-app/commit/325a308163040c1a3be03f355cd2d2697431db52
