### ISSUE TITLE
parsearguments.cmake is unnecessary

### ISSUE THREAD

**Issue by lodle** [desura/desura-app#469]
_Issue by **[harmonise](https://github.com/harmonise)** from Tuesday Feb 12, 2013 at 04:14 GMT_
_Originally opened as https://github.com/desura/Desurium/issues/469_

----

cmake/modules/parsearguments.cmake is obsolete since CMake 2.8.3 where it was replaced by CMakeParseArguments.cmake. As we require at least CMake 2.8.5 there should be no issues with moving to CMakeParseArguments.cmake.

**Comment by TheBeastie** [comment]
Assuming closed?
