### ISSUE TITLE
Failed to download banner: The url  is not a valid http url 

### ISSUE THREAD

**Issue by lodle** [desura/desura-app#553]
_Issue by **[Mailaender](https://github.com/Mailaender)** from Saturday May 25, 2013 at 16:38 GMT_
_Originally opened as https://github.com/desura/Desurium/issues/553_

----

This message is always spammed in the Debug Console whenever I download anything. However the banners (blue, include number and location of the Desura server) seem to be loaded properly so this just irritating.

**Comment by TheBeastie** [comment]
Fixed:
https://github.com/desura/desura-app/commit/2419b79a07b51501a003a67e64b0cfd6602ad138
