### ISSUE TITLE
desurium freezes while game is running

### ISSUE THREAD

**Issue by lodle** [desura/desura-app#566]
_Issue by **[TheSiege](https://github.com/TheSiege)** from Thursday Jun 13, 2013 at 15:25 GMT_
_Originally opened as https://github.com/desura/Desurium/issues/566_

----

console output: http://pastebin.com/CnuR88bX
all is delayed until game is exited

**Comment by TheBeastie** [comment]
Fixed in desura-app linux:
https://github.com/desura/desura-app/commit/a127bdd545a2b520524e9fa65a5ceec6a3cc753c
