### ISSUE TITLE
[CLOSED] mcf_upload_cli does nothing 

### ISSUE THREAD

**Issue by lodle** [desura/desura-app#579]
_Issue by **[Mailaender](https://github.com/Mailaender)** from Thursday Aug 08, 2013 at 14:31 GMT_
_Originally opened as https://github.com/desura/Desurium/issues/579_

---

I tried **mcf_upload_cli -u myusername -p mypassword -f /home/matthias/Projekte/OpenRA/packaging/linux/root/usr/share/openra/ -i 14718 -t games** and it does just nothing. No response that it aborted or completed. I guess it failed because it exits too fast and http://www.desura.com/games/publish/openra/execute stays empty. Unsure how to investigate and fix this also in regard of #550.

---
##  MCF Upload Utility By @Lodle

Usage:
        --username (-u): Desura Username
        --password (-p): Desura Password
        --folder (-f): Folder of game files
        --item (-i): Item site area id
        --type (-t): Item site area (mods | games)

**Comment by Mailaender** [comment]
Why is this closed. I lost an overview, because you copied these issue so much, but so far I guess nothing has been fixed and there is no 0.91 release after two years. Is this project dead?
