### ISSUE TITLE
Linux fails to exit cleanly when libunittests.so is loaded

### ISSUE THREAD

**Issue by lodle** [desura/desura-app#701]
_Issue by **[lodle](https://github.com/lodle)** from Wednesday Oct 30, 2013 at 16:12 GMT_
_Originally opened as https://github.com/desura/Desurium/issues/701_

----

After applying this fix https://github.com/lodle/Desurium/commit/777388c7617340cfb8b18df240eb7a2d380560bc linux segfaults on exit. Looks like the libunittests.so is getting unloaded but not de-registering its unit tests

**Comment by TheBeastie** [comment]
Looking at UICoreEntry.cpp in the current desura-app, I do not think this still applies.
