### ISSUE TITLE
64 bit version forcibly installs wine-silverlight5.1-installer package

### ISSUE THREAD

**Issue by lodle** [desura/desura-app#709]
_Issue by **[Todd102030](https://github.com/Todd102030)** from Sunday Nov 03, 2013 at 20:05 GMT_
_Originally opened as https://github.com/desura/Desurium/issues/709_

----

Why does it do this? The 32 bit version doesn't, and I can't understand why Silverlight would even be needed.

This is the output I get when running Desurium for the first time after completely purging it and the silverlight packages

http://pastebin.com/CbrA9pje

**Comment by TheBeastie** [comment]
I do not believe this is currently applicable on the Linux desura-app
