### ISSUE TITLE
What are real Linux dependencies?

### ISSUE THREAD

**Issue by makson96** [desura/desura-app#773]
With my latest pull request README.md reflects what CMakeLists.txt is looking for. However there are many unsorted things.
In README.md
- Freetype

is listed as a dependency, but it is not looked for by cmake, nor it appears enywhere in install_deps.sh. So do we need it or not?

The second thing is, that there are many dependencies in install_deps.sh which do not appear in CMakeLists.txt nor in README.md. I will list them below. We must figure out, which of them do we really need and add appropriate check for cmake:
- alsa-lib
- autoconf
- automake
- bison
- flac
- flex
- gconf
- gperf
- libasound2
- cups (seriously?)
- gnome-keyring
- libjpeg (version 62 - for CEF)
- libpng
- libtool
- libxml2 (don't mistake with tinyxml2)
- libxpm
- libxslt
- libxxf86vm
- m4
- nss
- <del>scons<del>
- speex
- xdg-utils
- yasm
- zlib

**Comment by TheBeastie** [comment]
Dependencies for the Linux build were added.   If we missed anything, please create a new issue for it.
ty.
