### ISSUE TITLE
[question] releases

### ISSUE THREAD

**Issue by hasufell** [desura/desura-app#825]
Are there going to be releases or will this rather be rolling-release directly from git HEAD?

**Comment by hasufell** [comment]
Closed without comment?

**Comment by jeffjirsa** [comment]
@hasufell - right now, we're doing rolling releases from HEAD, which get built and fed into Desura.com as MCF files, which then get pushed to users as MCF updates (the same format used to download games). Actual releases may come in the future as we work with various distributions to get meaningful installers/packages into their systems.

**Comment by liamdawe** [comment]
Interesting J, how does the Linux client update currently? As I see a few reports closed, so if I boot up Desura one day soon will it auto-update?

**Comment by jeffjirsa** [comment]
@liamdawe Yes - The linux client now polls the API the same as the Windows client, when new versions are pushed up via CI, a popup will show and allow you to restart the client with new unpacked binaries.

**Comment by hasufell** [comment]
That sounds terrible for anyone who wants to compile from source and will practically make it impossible to package desura. I hope you make this in-place autoupdates optional.

**Comment by jeffjirsa** [comment]
@hasufell The auto-update is optional, and updates can be declined. Should not prevent anyone from building from source and packaging.

**Comment by hasufell** [comment]
Cool.
