### ISSUE TITLE
Home directory not set?

### ISSUE THREAD

**Issue by liamdawe** [desura/desura-app#967]
When loading via terminal, this error comes up:

liam@liam-mint ~ $ '/home/liam/Downloads/desura/desura' 
$XDG_CONFIG_HOME not set, falling back to $HOME/.config.$XDG_CACHE_HOME not set, falling back to $HOME/.cache.Saving crash report to: /home/liam/.desura/crash_log.txt

Not serious, but may be nice to clean it up a little? Not sure if that's my issue or yours to be honest.

**Comment by codethulu** [comment]
As far as I can tell, it's on us. This appears to be non-fatal and reverts to a sane default.

Likely solution is to add that XDG_CONFIG_HOME to the environment in the launch script.

**Comment by codethulu** [comment]
https://github.com/desura/desura-app/pull/1006
