### ISSUE TITLE
Installing a game, checks old data files

### ISSUE THREAD

**Issue by liamdawe** [desura/desura-app#970]
I tried to install Majesty Gold for the first time since installing Desura on this PC.

It decided to check old data files, which took a long while even though i had not downloaded any game yet (this was my first try after my other error reports).

Seems like a highly un-needed step.

**The biggest issue of all: It didn't seem to want to install, it just got stuck after validating all files**.

I tried on a few others, no validation, but **it won't install anything**. After trying two others this happened:
/home/liam/Downloads/desura/lib/lib/lib/lib/lib/desura: line 21:  5523 Segmentation fault      $DESURA_DEBUGGERS $DIR/lib/desura $@

Is there not a way to check a simple file say "majesty gold" in a "games downloaded" folder, if it exists, check old files, if not, don't. Simple, and should work fine. Something like that anyway.

Not fool-proof, but that's what your checking is for.

**Comment by Tokiolabs** [comment]
Oddly, that's exactly the way it's supposed to work in terms of the code.  Desura passes a variable that looks for the install file; but typically won't be looking for all the files.  The nested /libs are odd; but this drives to the heart of the seg fault.  Will take a look at that.

**Comment by liamdawe** [comment]
Well until this is fix the client is a bit useless. Since it won't install anything :(

If you need any further info let me know the steps to take.

**Comment by Tokiolabs** [comment]
Totally agree... Working on this one today.  I imagine this isn't a huge problem (hopefully)

**Comment by liamdawe** [comment]
Fantastic. As I really want it to succeed, but obviously can't recommend it right now.

If you need more testing just holla.

**Comment by liamdawe** [comment]
Any news on this?

**Comment by TheBeastie** [comment]
Sorry, we are still investigating this internally.  I will post info on this as soon as we have something.

**Comment by robertxgray** [comment]
I am being able to install games, but it requires several attempts and when it fails the errors seem random. I'll write again if I can get to a more useful diagnose.

**Comment by liamdawe** [comment]
So, I've left it a week before asking, but are you any closer to solving it?

**Comment by codethulu** [comment]
Games installing was just patched in, and should be public soon. Root cause was not following a web redirect to the zipped libs.

**Comment by liamdawe** [comment]
Excellent, let us know when it's up and in the client download :D

**Comment by codethulu** [comment]
Presently live.
