### ISSUE TITLE
Arch Linux Install issue

### ISSUE THREAD

**Issue by TheBeastie** [desura/desura-app#974]
I managed to make the desura client start by deleting all the provided libs except these ones:
libboost_date_time-desura.so.1.47.0 libboost_thread-desura.so.1.47.0
libboost_filesystem-desura.so.1.47.0 libcurl_desura.so.4
libboost_filesystem.so.1.54.0 libcurl.so.4
libboost_system-desura.so.1.47.0 libgnutls.so.26
libboost_system.so.1.54.0 librtmp.so.0
(on Arch)

But it starts the updater so I suppose that will restore all the wrong libs and crash again.

**Comment by TheBeastie** [comment]
From another Arch user:

Anyone else getting segmentation fault on arch linux ? It's the 64 bit client.

This is what i get when trying to run:

./desura: line 21: 13266 Segmentation fault $DESURA_DEBUGGERS $DIR/lib/desura $@

I'm on regular arch rolling non of the derivatives kernel 3.17, gnome shell nothing fancy when it crashed running a vm instance and browser. Going to see how the client behaves on my other kubuntu 14.04 box.

Edit:

No problems on kubuntu so far.

**Comment by TheBeastie** [comment]
From another Arch user:

I detect an error after installation, i try to run desura:
commande: ./desura (in the installation directory)
./desura : ligne 21 : 15085 Erreur de segmentation  (core dumped)$DESURA_DEBUGGERS $DIR/lib/desura $@


So i'm under Archlinux, and this is the information i can find, "Linux 3.17.6-1-ARCH x86_64 GNU/Linux". If you need more information don't hesitate i can look for.

And the problem is before anythings, i just can't launch desura, so no loading or log.
I copy the exact command and reply of my terminal.
Then i notify a change in the number of reply for example i sent you:
./desura : ligne 21 : 15085 Erreur de segmentation  (core dumped)$DESURA_DEBUGGERS $DIR/lib
But when i retry i have:
./desura : ligne 21 :  7056 Erreur de segmentation  (core dumped)$DESURA_DEBUGGERS
or
./desura : ligne 21 :  7047 Erreur de segmentation  (core dumped)$DESURA_DEBUGGERS
And more, i always have a different number

**Comment by robertxgray** [comment]
I had the same problem in openSUSE Tumbleweed, but it was solved by replacing libc.so.6 and libdl.so.2 in the lib folder with the versions provided by my distribution.

**Comment by TheBeastie** [comment]
Robert, we have updated the Linux Desura App to 120.25, which should have fixed some installation crashes (specifically those wrong libraries being included) and various crashes while running.   Would you mind seeing if this version works for you?

**Comment by robertxgray** [comment]
Yes, no more segfaults anymore. Only two issues, I had to install libboost_filesystem 1.54 because my distribution is shipping 1.57 by default, I suppose this won't affect most users now, but may in the future. 

The other issue is libbz2.so.1.0 not being available in openSUSE, this is the same in other rpm based distributions like Fedora or Mageia (my source is http://pkgs.org), could you consider using libbz2.so.1 instead?

**Comment by codethulu** [comment]
This issue should be resolved in 320.31/120.26. Please re-open if this issue persists after updating.

**Comment by robertc** [comment]
Still getting this error on Fedora 20 x64:

/desura/lib/desura: error while loading shared libraries: libbz2.so.1.0: cannot open shared object file: No such file or directory
