### ISSUE TITLE
Arch Linux: cannot install games

### ISSUE THREAD

**Issue by TheBeastie** [desura/desura-app#975]
Whenever I try to install the game with the Linux client I get this output:
16:03 Error in MCF validate: The size was zero [11.0]
16:03 There was an error during the validation process and it has been stopped.: The size was zero [11.0]

Here are my (overly detailed) system specficiations:
Distribution: Arch Linux
Graphics Driver: R600 Gallium3D Driver
Desktop Environment: Xfce with compositing
Motherboard: MSI 760GM-E51(FX)
Processor: AMD Phenom II X4 955 BE 3.2 Ghz
Video Card: Sapphire Radeon HD 6870
Memory: 4 Gigabytes DDR3 PC10666, 1333 MHz
Boot Drive: 500 GB Western Digital Caviar Black
Headset: Roccat Kulo ROC-14-702

**Comment by robertxgray** [comment]
I get this error message with my old Desurium installation (0.8.0_rc10), the new client just started working when I found a workaround for #974 and a game is downloading right now, fingers crossed.

**Comment by codethulu** [comment]
This issue should be resolved in 320.31/120.26. Please re-open if this issue persists after updating.

**Comment by Zenitur** [comment]
It's appearing in fresh install! Desurium and Desurium-cef from today's GIT.

![-desurium linux 64 zenitur](https://cloud.githubusercontent.com/assets/3435752/6423635/3371b24a-bf13-11e4-9fd3-6dc1f6bef539.png)
