### ISSUE TITLE
Linux: Issue with MCF upload

### ISSUE THREAD

**Issue by TheBeastie** [desura/desura-app#979]
The 520.120 version of the client seems to be doing something different I haven't seen it do before. I uploaded a MCF, then went to test it and it went through "Checking old data file: Stage 0" then just seems to sit there after counting through everything. I never had it do that before when I tested a new MCF upload.

**Comment by Braqoon** [comment]
Version 120.25 works fine. Tested with two MCF builds and uploads.

**Comment by codethulu** [comment]
This issue should be resolved in 320.31/120.26. There was an issue uploading MCFs over a certain size. Please re-open if this issue persists after updating.
