### ISSUE TITLE
'CURL_OPENSSL_3' not found - Manjaro x64

### ISSUE THREAD

**Issue by tsaber** [desura/desura-app#992]
Hi when I try to start Desura I get this

/home/tsabehr/Downloads/desura/lib/desura: /usr/lib/libcurl.so.4: version `CURL_OPENSSL_3' not found (required by /home/tsabehr/Downloads/desura/lib/desura)

before it asked for 2 other libs but them I installed

curl as well as lib32-curl however is installed

Thanks

**Comment by codethulu** [comment]
This issue should be resolved in 320.31/120.26. Please re-open if this issue persists after updating.
