### ISSUE TITLE
Opted into beta, closed, reloaded, error

### ISSUE THREAD

**Issue by liamdawe** [desura/desura-app#998]
So, I select to opt into the beta from the beta settings tab even though I'm not sure it does anything...just thought I would try.

Now I get this when trying to load Desura:
http://i.imgur.com/YifBNr5.png

Happens every time, a very unfriendly error, it could at least tell me what to remove if/when it fails.

**Comment by codethulu** [comment]
the file it doesn't like is desura_update.mcf
